general {
  gaps_in = 4
  gaps_out = 8

  border_size = 2

  col.active_border = rgba(bb9af7ee)
  col.inactive_border = rgba(565f89aa)

  resize_on_border = true
  allow_tearing = false

  layout = dwindle
}

group {
  col.border_active = rgba(bb9af7ee)
  col.border_inactive = rgba(565f89aa)
  col.border_locked_active = rgba(ff5555ff)

  groupbar {
    height = 16
    indicator_gap = 8

    col.active = rgba(bb9af7ee)
    col.inactive = rgba(565f89aa)
    
    text_color = rgba(bb9af7ee)
    text_color_inactive = rgba(565f89aa)

    font_size = 14
    font_family = JetBrainsMono NF
    font_weight_active = bold

    blur = true
  }
}

decoration {
  rounding = 16
  rounding_power = 2

  active_opacity = 1.0
  inactive_opacity = 1.0

  blur {
    enabled = true
    size = 6
    passes = 4
    new_optimizations = true
    ignore_opacity = true
    xray = false
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
    popups = true
    popups_ignorealpha = 0.2
    input_methods = true
    special = true
  }
}

dwindle {
  pseudotile = true
  preserve_split = true
}

master {
  new_status = master
}

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
}

cursor {
  inactive_timeout = 5
  warp_on_change_workspace = true
}

input {
  kb_rules = evdev
  kb_model = pc105
  kb_layout = us,es

  follow_mouse = 1
  sensitivity = 0

  touchpad {
    natural_scroll = true
  }
}

gesture = 3, horizontal, workspace

device {
  name = epic-mouse-v1
  sensitivity = -0.5
}

xwayland {
  force_zero_scaling = true
}
