format = """
[╭──](fg:blue) $os$username$directory $git_branch$git_status
[╰──](fg:blue)$character"""

command_timeout = 5001
add_newline = true

[os]
format = "[$symbol](bold fg:blue)"
disabled = false

[os.symbols]
Windows = " "
Arch = "󰣇 "

[username]
style_user = "fg:#ffffff bold bg:purple bold"
style_root = "#ffffff bold"
format = "[](bold fg:purple)[$user]($style)[ ](bold fg:purple)"
disabled = false
show_always = true

[directory]
style = "bg:purple fg:#ffffff"
format = '󰜥 [](bold fg:purple)[󰉋 $path]($style)[](bold fg:purple)'

[character]
success_symbol = "[](bold fg:blue)"
error_symbol = "[](bold fg:red)"

[git_branch]
style = "bg: cyan"
symbol = "󰘬"
truncation_length = 13
truncation_symbol = ""
format = "[](bold fg:purple)[$symbol $branch(:$remote_branch)](fg:#ffffff bg:purple)[ ](bold fg:purple)"
