foreground              #d1d1d1
background              #030107
selection_foreground    #030107
selection_background    #a77ef5
cursor                  #d1d1d1
cursor_text_color       #030107
url_color               #5b70db
active_border_color     #a77ef5
inactive_border_color   #484d69
bell_border_color       #f0a32f
active_tab_foreground   #030107
active_tab_background   #a77ef5
inactive_tab_foreground #d1d1d1
inactive_tab_background #030107
tab_bar_background      #030107
color0  #484d69
color8  #484d69
color1  #e52e4f
color9  #e52e4f
color2  #86c93f
color10 #86c93f
color3  #f0a32f
color11 #f0a32f
color4  #5b70db
color12 #5b70db
color5  #a77ef5
color13 #a77ef5
color6  #72cbff
color14 #72cbff
color7  #d1d1d1
color15 #d1d1d1
